/**
 * CreateScreen — /create
 *
 * Admin-only page. Generates a random 4-digit room code and claims host
 * ownership on the server via cookie-backed session.
 */
import { useEffect, useReducer, useRef } from "react";
import { useNavigate } from "../router";
import { useGameDispatch, useGameState, useWsSend } from "../state/store";
import QRCode from "./QRCode";

interface LocalState {
  code: string | null;
}

type LocalAction = { type: "generate_with_code"; code: string };

function localReducer(_state: LocalState, action: LocalAction): LocalState {
  switch (action.type) {
    case "generate_with_code":
      return { code: action.code };
  }
}

export default function CreateScreen() {
  const navigate = useNavigate();
  const gameDispatch = useGameDispatch();
  const send = useWsSend();
  const { gameCode, knownPlayers } = useGameState();
  const [local, dispatch] = useReducer(localReducer, { code: gameCode });
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    // Keep create-page code aligned with server-restored session code.
    if (gameCode && gameCode !== local.code) {
      dispatch({ type: "generate_with_code", code: gameCode });
    }
  }, [gameCode, local.code]);

  useEffect(() => {
    if (local.code || gameCode || hasAutoGeneratedRef.current) {
      return;
    }
    hasAutoGeneratedRef.current = true;
    const code = String(Math.floor(1000 + Math.random() * 9000));
    claimHostLobby(code, false);
  }, [gameCode, local.code]);

  function claimHostLobby(code: string, navigateToHost: boolean) {
    fetch("/api/session/host", {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ game_code: code }),
    })
      .then((r) => r.json())
      .then((data: { game_code?: string | null }) => {
        const resolvedCode = data.game_code ?? code;
        gameDispatch({ type: "set_game_code", code: resolvedCode });
        gameDispatch({ type: "set_host" });
        dispatch({ type: "generate_with_code", code: resolvedCode });
        if (navigateToHost) {
          navigate("/host");
        }
      })
      .catch(() => {
        // Fallback to requested code if the response is unavailable.
        gameDispatch({ type: "set_game_code", code });
        gameDispatch({ type: "set_host" });
        dispatch({ type: "generate_with_code", code });
      });
  }

  return (
    <div style={styles.root}>
      <h1 style={styles.title}>🌽 Aura Farmers</h1>

      {!local.code ? (
        <p style={styles.sub}>Preparing your host room...</p>
      ) : (
        <div style={styles.codeBlock}>
          <QRCode value={`${window.location.origin}/${local.code}`} style={styles.qrImg} />
          <div style={styles.code}>{local.code}</div>
          <p style={styles.hint}>Enter this code on the join page</p>

          {/* ── Waiting players ──────────────────────────────────────────── */}
          <div style={styles.roster}>
            <p style={styles.rosterTitle}>
              Players waiting ({knownPlayers.length})
            </p>
            {knownPlayers.length === 0 ? (
              <p style={styles.rosterEmpty}>No one has joined yet.</p>
            ) : (
              <div style={styles.rosterList}>
                {knownPlayers.map((p, i) => (
                  <div key={p.id} style={styles.rosterRow}>
                    <span style={styles.rosterNum}>{i + 1}</span>
                    <span style={styles.rosterName}>{p.name}</span>
                    <span
                      style={{
                        ...styles.rosterRole,
                        color: p.role === "farmer" ? "#1d6b1d" : "#0d5858",
                      }}
                    >
                      {p.role}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div style={styles.actions}>
            <button
              style={styles.btn}
              onClick={() => {
                // Upgrade this WS connection to host role, then start the game.
                send({ type: "claim_host" });
                gameDispatch({ type: "set_host" });
                send({ type: "admin", command: { cmd: "start_game" } });
                navigate("/host");
              }}
            >
              Start Match →
            </button>
            <button
              style={{ ...styles.btn, background: "#f5f3ef", color: "#6b6b63", border: "1.5px solid #e2ddd6" }}
              onClick={() => {
                const code = String(Math.floor(1000 + Math.random() * 9000));
                claimHostLobby(code, false);
              }}
            >
              New Code
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  root: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    gap: "1.25rem",
    padding: "1.5rem 1rem",
    background: "#f5f3ef",
  },
  title: { fontSize: "2.2rem", margin: 0, color: "#18181a", fontWeight: "800" as const, letterSpacing: "-0.02em" },
  sub: { color: "#8a8a80", textAlign: "center" as const, maxWidth: 360, margin: 0, fontSize: "0.9rem" },
  btn: {
    background: "#1d6b1d",
    color: "#fff",
    border: "none",
    padding: "0.7rem 1.5rem",
    borderRadius: 8,
    fontFamily: "inherit",
    fontSize: "0.95rem",
    cursor: "pointer",
    fontWeight: "700" as const,
  },
  codeBlock: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "0.75rem",
    background: "#ffffff",
    border: "1px solid #e2ddd6",
    borderRadius: 12,
    padding: "1.5rem 1.25rem",
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  code: {
    fontSize: "3.5rem",
    fontWeight: "800" as const,
    letterSpacing: "0.25em",
    color: "#1d6b1d",
  },
  hint: { color: "#8a8a80", fontSize: "0.8rem", margin: 0, textAlign: "center" as const },
  qrImg: {
    width: "clamp(140px, 16vw, 220px)",
    height: "auto",
    borderRadius: 6,
    display: "block",
  },
  roster: {
    alignSelf: "stretch" as const,
    borderTop: "1px solid #e8e4df",
    paddingTop: "0.75rem",
    marginTop: "0.25rem",
  },
  rosterTitle: {
    margin: "0 0 0.5rem",
    fontSize: "0.75rem",
    color: "#8a8a80",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  rosterEmpty: { margin: 0, fontSize: "0.85rem", color: "#b0aea8" },
  rosterList: { display: "flex", flexDirection: "column" as const, gap: "0.35rem" },
  rosterRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    fontSize: "0.9rem",
  },
  rosterNum: { color: "#b0aea8", fontSize: "0.75rem", width: 16 },
  rosterName: { flex: 1, color: "#3a3a36" },
  rosterRole: { fontSize: "0.75rem" },
  actions: { display: "flex", gap: "0.75rem", marginTop: "0.5rem" },
} as const;
