/**
 * Global game state.
 *
 * Pattern: useReducer + two contexts (read vs write) so components that only
 * read state don't re-render when dispatch identity changes, and vice versa.
 *
 * Usage in any component:
 *   const state = useGameState();
 *   const dispatch = useGameDispatch();
 *   const send = useWsSend();
 */
import { createContext, Dispatch, useContext } from "react";
import type {
  Farm,
  Mill,
  NpcOwner,
  GameEvent,
  ServerMsg,
  DebriefStats,
} from "../ws/protocol";

// ── State shape ───────────────────────────────────────────────────────────────

export type Phase =
  | "lobby"
  | "decision"
  | "resolving"
  | "summary"
  | "game_over";

export interface GameState {
  // Connection / identity
  connected: boolean;
  isHost: boolean; // true = watching only, never joins as a player
  myPlayerId: number | null;
  myName: string;
  myRole: string;
  // Set when the user clicks Join; cleared once the matching welcome arrives.
  pendingJoinNonce: string | null;
  // All players seen via Welcome broadcasts (used by host view)
  knownPlayers: Array<{ id: number; name: string; role: string }>;

  // Cycle
  phase: Phase;
  cycle: number;
  secondsRemaining: number;

  // Market
  price: string; // Decimal serialised as string — parse with parseFloat() for display
  priceHistory: string[];
  volumeHistory: number[];
  bidDepth: number;
  askDepth: number;
  cycleVolume: number;

  // My portfolio
  myCash: string;
  myShares: number;
  myAura: number;
  myNetWorth: string;

  // World
  farms: Farm[];
  mills: Mill[];
  npcOwners: NpcOwner[];

  // Events & narrative
  cycleEvents: GameEvent[]; // events from the most recent resolved cycle
  headlines: Array<{ text: string; cycle: number }>; // last 20

  // Per-cycle AI coaching (only current player's tip kept)
  myFeedback: string | null;

  // Per-cycle admin summary (Sonnet, only visible to admin/host)
  adminSummary: { text: string; cycle: number } | null;
  // Milestone (every-5-cycle) summary — broadcast to all players
  milestoneSummary: { text: string; cycle: number } | null;

  // All players' net worths — populated from PlayerState broadcasts (host uses this for leaderboard)
  playerNetWorths: Record<number, { name: string; netWorth: string }>;
  // Latest option strike list per player from PlayerState updates.
  playerOptionStrikes: Record<number, string[]>;
  // Latest option positions per player for strike-level host summaries.
  playerOptionPositions: Record<
    number,
    Array<{ strike: string; long: boolean; quantity: number }>
  >;

  // End-of-game structured stats (no LLM)
  debrief: DebriefStats | null;
  // End-of-game narrative recap from LLM — arrives a few seconds after debrief
  debriefNarrative: string | null;

  // UI feedback
  error: string | null;

  // Room code generated by the host — shown on HostScreen and JoinScreen
  gameCode: string | null;

  // Pause state (host can pause/resume the decision timer)
  paused: boolean;

  // Increments on every game_reset — used to detect when a reset happened.
  resetCount: number;
}

const INITIAL_STATE: GameState = {
  connected: false,
  isHost: false,
  myPlayerId: null,
  myName: "",
  myRole: "",
  pendingJoinNonce: null,
  knownPlayers: [],
  phase: "lobby",
  cycle: 0,
  secondsRemaining: 0,
  price: "100",
  priceHistory: [],
  volumeHistory: [],
  bidDepth: 0,
  askDepth: 0,
  cycleVolume: 0,
  myCash: "0",
  myShares: 0,
  myAura: 0,
  myNetWorth: "0",
  farms: [],
  mills: [],
  npcOwners: [],
  cycleEvents: [],
  headlines: [],
  myFeedback: null,
  adminSummary: null,
  milestoneSummary: null,
  playerNetWorths: {},
  playerOptionStrikes: {},
  playerOptionPositions: {},
  debrief: null,
  debriefNarrative: null,
  error: null,
  gameCode: null,
  paused: false,
  resetCount: 0,
};

// ── Actions ───────────────────────────────────────────────────────────────────

export type GameAction =
  // Fired by useWs when the socket opens/closes
  | { type: "ws_connected" }
  | { type: "ws_disconnected" }
  // Every ServerMsg is wrapped and forwarded here
  | { type: "server_msg"; msg: ServerMsg }
  // Mark this client as the host/spectator (never joins as player)
  | { type: "set_host" }
  // Store the room code generated by the host
  | { type: "set_game_code"; code: string }
  // Local UI action to dismiss the error banner
  | { type: "clear_error" }
  // Dismiss the current cycle's coaching tip
  | { type: "clear_feedback" }
  // Dismiss the admin summary panel
  | { type: "clear_admin_summary" }
  // Set before sending a join message so the client can claim only its own welcome
  | { type: "set_join_nonce"; nonce: string }
  // Clear the host flag (e.g. after game_reset so old sessions don't linger)
  | { type: "clear_host" }
  // Player voluntarily leaves the game (clears player identity, returns to join)
  | { type: "leave_game" };

// ── Reducer ───────────────────────────────────────────────────────────────────

function reducer(state: GameState, action: GameAction): GameState {
  switch (action.type) {
    case "ws_connected":
      return { ...state, connected: true };

    case "ws_disconnected":
      return { ...state, connected: false };

    case "clear_error":
      return { ...state, error: null };

    case "set_host":
      return { ...state, isHost: true };

    case "set_game_code":
      return { ...state, gameCode: action.code };

    case "clear_feedback":
      return { ...state, myFeedback: null };

    case "clear_admin_summary":
      return { ...state, adminSummary: null };

    case "clear_host":
      return { ...state, isHost: false, gameCode: null };

    case "leave_game":
      return {
        ...state,
        myPlayerId: null,
        myName: "",
        myRole: "",
        gameCode: null,
        error: null,
      };

    case "set_join_nonce":
      return { ...state, pendingJoinNonce: action.nonce };

    case "server_msg": {
      const msg = action.msg;
      switch (msg.type) {
        case "welcome": {
          const entry = { id: msg.player_id, name: msg.name, role: msg.role };
          // Host: track everyone.
          if (state.isHost) {
            return { ...state, knownPlayers: [...state.knownPlayers, entry] };
          }
          // Already joined as a player — ignore others' welcomes entirely.
          if (state.myPlayerId !== null) return state;
          // Only claim the welcome that matches the nonce we sent.
          if (
            state.pendingJoinNonce === null ||
            msg.client_nonce !== state.pendingJoinNonce
          ) {
            return state;
          }
          return {
            ...state,
            myPlayerId: msg.player_id,
            myName: msg.name,
            myRole: msg.role,
            pendingJoinNonce: null,
          };
        }

        case "price_update":
          // Keep a rolling volume series aligned to incoming price history length.
          // Server currently emits latest cycle_volume, so we append it over time.
          const nextVolumeHistory = [
            ...state.volumeHistory,
            msg.cycle_volume,
          ].slice(-Math.max(msg.history.length, 1));
          return {
            ...state,
            price: msg.price,
            priceHistory: msg.history,
            volumeHistory: nextVolumeHistory,
            bidDepth: msg.bid_depth,
            askDepth: msg.ask_depth,
            cycleVolume: msg.cycle_volume,
          };

        case "cycle_phase":
          return {
            ...state,
            phase: msg.phase as Phase,
            cycle: msg.cycle,
            secondsRemaining: msg.seconds_remaining,
            // Clear stale events and feedback at the start of a new decision window.
            cycleEvents: msg.phase === "decision" ? [] : state.cycleEvents,
            myFeedback: msg.phase === "decision" ? null : state.myFeedback,
          };

        case "world_snapshot":
          return {
            ...state,
            farms: msg.farms,
            mills: msg.mills,
            npcOwners: msg.npc_owners,
          };

        case "cycle_events":
          return { ...state, cycleEvents: msg.events };

        case "player_state": {
          // Track net worth for all players (host leaderboard) regardless of identity.
          const updatedNetWorths = {
            ...state.playerNetWorths,
            [msg.player_id]: { name: msg.name, netWorth: msg.net_worth },
          };
          const updatedOptionStrikes = {
            ...state.playerOptionStrikes,
            [msg.player_id]: msg.options.map((o) => o.strike),
          };
          const updatedOptionPositions = {
            ...state.playerOptionPositions,
            [msg.player_id]: msg.options.map((o) => ({
              strike: o.strike,
              long: o.long,
              quantity: o.quantity,
            })),
          };
          if (msg.player_id !== state.myPlayerId) {
            return {
              ...state,
              playerNetWorths: updatedNetWorths,
              playerOptionStrikes: updatedOptionStrikes,
              playerOptionPositions: updatedOptionPositions,
            };
          }
          return {
            ...state,
            myCash: msg.cash,
            myShares: msg.shares,
            myAura: msg.aura,
            myNetWorth: msg.net_worth,
            playerNetWorths: updatedNetWorths,
            playerOptionStrikes: updatedOptionStrikes,
            playerOptionPositions: updatedOptionPositions,
          };
        }

        case "player_feedback":
          // Only store feedback addressed to this player.
          if (msg.player_id !== state.myPlayerId) return state;
          return { ...state, myFeedback: msg.tips };

        case "headline":
          return {
            ...state,
            headlines: [
              ...state.headlines.slice(-19),
              { text: msg.text, cycle: msg.cycle },
            ],
          };

        case "admin_summary":
          return {
            ...state,
            adminSummary: { text: msg.text, cycle: msg.cycle },
          };

        case "milestone_summary":
          return {
            ...state,
            milestoneSummary: { text: msg.text, cycle: msg.cycle },
          };

        case "player_roster":
          return {
            ...state,
            knownPlayers: msg.players.map((p) => ({
              id: p.player_id,
              name: p.name,
              role: p.role,
            })),
          };

        case "player_left":
          return {
            ...state,
            knownPlayers: state.knownPlayers.filter(
              (p) => p.id !== msg.player_id,
            ),
          };

        case "kicked":
          if (msg.player_id === state.myPlayerId) {
            return {
              ...state,
              myPlayerId: null,
              myName: "",
              myRole: "",
              error: `Kicked: ${msg.reason}`,
            };
          }
          return state;

        case "game_paused":
          return { ...state, paused: true };

        case "game_resumed":
          return {
            ...state,
            paused: false,
            secondsRemaining: msg.seconds_remaining || state.secondsRemaining,
          };

        case "debrief":
          return { ...state, debrief: msg.stats };

        case "debrief_narrative":
          return { ...state, debriefNarrative: msg.text };

        case "game_over":
          return { ...state, phase: "game_over" };

        case "game_reset":
          return {
            ...INITIAL_STATE,
            connected: state.connected,
            isHost: state.isHost,
            gameCode: state.gameCode,
            resetCount: state.resetCount + 1,
          };

        case "error":
          return { ...state, error: msg.message };

        default:
          return state;
      }
    }
  }
}

// ── Contexts ──────────────────────────────────────────────────────────────────

export const GameStateContext = createContext<GameState>(INITIAL_STATE);
export const GameDispatchContext = createContext<Dispatch<GameAction>>(
  () => {},
);
// WsSend is stored separately so screens can call send() without triggering a
// re-render cascade through GameDispatch.
export const WsSendContext = createContext<
  ((msg: import("../ws/protocol").ClientMsg) => void) | null
>(null);

// ── Hooks ─────────────────────────────────────────────────────────────────────

export function useGameState() {
  return useContext(GameStateContext);
}

export function useGameDispatch() {
  return useContext(GameDispatchContext);
}

/** Returns the typed send() function. Throws if called outside <App>. */
export function useWsSend() {
  const send = useContext(WsSendContext);
  if (!send) throw new Error("useWsSend must be used inside App");
  return send;
}

export { reducer, INITIAL_STATE };
