use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// One entry in the PlayerRoster snapshot.
#[derive(Debug, Clone, Serialize)]
pub struct RosterEntry {
    pub player_id: u64,
    pub name: String,
    pub role: String,
}

use crate::market::options::OptionPosition;
use crate::sim::actions::{AdminCommand, PlayerAction};
use crate::sim::entities::Role;
use crate::sim::entities::{Farm, Mill, NpcOwner};
use crate::sim::events::GameEvent;

// ── Debrief stats (computed, no LLM) ─────────────────────────────────────────

/// One row in the end-of-game leaderboard.
#[derive(Debug, Clone, Serialize)]
pub struct PlayerSummary {
    pub player_id: u64,
    pub name: String,
    pub role: String,
    pub net_worth: Decimal,
    /// net_worth − starting_cash
    pub pnl: Decimal,
    /// PnL / starting_cash × 100
    pub return_pct: f64,
    /// 1 = highest net worth
    pub rank: u32,
}

/// Structured end-of-game statistics sent in ServerMsg::Debrief.
/// Computed entirely from world state — no LLM.
#[derive(Debug, Clone, Serialize)]
pub struct DebriefStats {
    pub total_cycles: u64,
    pub final_price: f64,
    pub price_high: f64,
    pub price_low: f64,
    /// Cycle-to-cycle price volatility (std dev of simple returns, as a %)
    pub price_vol_pct: f64,
    pub mm_blowups: u32,
    pub game_over_reason: String,
    /// Sorted by net worth descending.
    pub leaderboard: Vec<PlayerSummary>,
}

// ── Server → Client ───────────────────────────────────────────────────────────

/// Messages sent from server → client.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMsg {
    // ── Connection ────────────────────────────────────────────────────────────
    Welcome {
        player_id: u64,
        name: String,
        role: String,
        /// Echoed from ClientMsg::Join so each client can claim only its own welcome.
        client_nonce: String,
    },

    // ── Market ───────────────────────────────────────────────────────────────
    PriceUpdate {
        price: Decimal,
        history: Vec<Decimal>,
        /// Shares resting on the bid side of the book.
        bid_depth: u32,
        /// Shares resting on the ask side of the book.
        ask_depth: u32,
        /// Shares that actually traded during the just-completed cycle.
        cycle_volume: u32,
    },

    // ── Cycle state ───────────────────────────────────────────────────────────
    CyclePhase {
        phase: String, // "decision" | "resolving"
        cycle: u64,
        seconds_remaining: u64,
    },

    // ── World snapshot (sent after each resolution) ───────────────────────────
    WorldSnapshot {
        farms: Vec<Farm>,
        mills: Vec<Mill>,
        npc_owners: Vec<NpcOwner>,
    },
    /// Per-cycle admin summary generated by the LLM (Sonnet). Host-only.
    AdminSummary {
        text: String,
        cycle: u64,
    },
    /// 5-cycle milestone recap — broadcast to all players. Generated when the
    /// game pauses at checkpoint cycles (5, 10, 15 …).
    MilestoneSummary {
        text: String,
        cycle: u64,
    },

    CycleEvents {
        cycle: u64,
        events: Vec<GameEvent>,
    },

    // ── Per-player state (broadcast to all; client filters on player_id) ──────
    PlayerState {
        player_id: u64,
        name: String,
        cash: Decimal,
        shares: i64,
        aura: f64,
        net_worth: Decimal,
        options: Vec<OptionPosition>,
    },

    // ── Per-player AI coaching (checkpoint cadence: every 5 cycles) ───────────
    /// Personalised financial education tip for one player.
    /// Broadcast to all; each client only displays their own.
    PlayerFeedback {
        player_id: u64,
        /// 2–3 bullet-point coaching tips from the LLM.
        tips: String,
    },

    // ── Narrator / debrief ───────────────────────────────────────────────────
    Headline {
        text: String,
        cycle: u64,
    },
    /// End-of-game summary — pure computed stats, no LLM.
    Debrief {
        stats: DebriefStats,
    },
    /// LLM narrative recap — awards, highlights, drama. Sent to all players.
    DebriefNarrative {
        text: String,
    },

    // ── Player roster (sent with every full state broadcast) ─────────────────
    /// Full player list — sent to all clients after every state flush.
    /// Non-host clients ignore this; hosts use it to rebuild the player table
    /// after reconnecting.
    PlayerRoster {
        players: Vec<RosterEntry>,
    },

    // ── Player lifecycle ─────────────────────────────────────────────────────
    /// Broadcast when any player disconnects so all clients can update their list.
    PlayerLeft {
        player_id: u64,
    },
    /// Sent to a specific player (via broadcast, client filters) when kicked by admin.
    Kicked {
        player_id: u64,
        reason: String,
    },

    // ── Pause / resume ────────────────────────────────────────────────────
    GamePaused {},
    GameResumed {
        seconds_remaining: u64,
    },

    // ── Game over ────────────────────────────────────────────────────────────
    GameOver {
        reason: String,
    },

    // ── Game reset (host restarted the game) ─────────────────────────────────
    GameReset {},

    // ── Error ────────────────────────────────────────────────────────────────
    Error {
        message: String,
    },
}

// ── Client → Server ───────────────────────────────────────────────────────────

/// Messages sent from client → server.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMsg {
    /// First message after connecting.
    Join {
        name: String,
        role: Role,
        client_nonce: String,
        /// 4-digit game code generated by the host.
        game_code: String,
    },
    /// Submit an action for this decision phase.
    Action { action: PlayerAction },
    /// Admin commands (authorised by a secret or just by being localhost in the hackathon).
    Admin { command: AdminCommand },
    /// Keep-alive (no-op, client-side ping).
    Ping,
    /// Player voluntarily leaves the game — removes them from the world.
    Leave,
}
