#!/usr/bin/env bash
# Provisions AWS + Cloudflare infrastructure via Terraform, then writes
# .env (prod) and development.env (local) from Terraform outputs.
#
# Usage: ./scripts/provision-infrastructure.sh
# Prerequisites:
#   - terraform installed and in PATH
#   - AWS credentials configured (aws configure / AWS_PROFILE / env vars)
#   - terraform/terraform.tfvars populated (copy from terraform.tfvars.example)

set -euo pipefail

export AWS_PROFILE="${AWS_PROFILE:-personal}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"

# ── 1. Terraform: provision infrastructure ───────────────────────────────────

echo "==> Initialising Terraform..."
terraform -chdir="$TF_DIR" init -upgrade

echo "==> Validating Terraform config..."
terraform -chdir="$TF_DIR" validate

echo "==> Applying Terraform (this may take a minute)..."
terraform -chdir="$TF_DIR" apply -auto-approve

# ── 2. Read Terraform outputs ────────────────────────────────────────────────

echo "==> Reading Terraform outputs..."

aws_region=$(terraform     -chdir="$TF_DIR" output -raw aws_region)
instance_ip=$(terraform    -chdir="$TF_DIR" output -raw instance_ip)
instance_name=$(terraform  -chdir="$TF_DIR" output -raw instance_name)
ssh_user=$(terraform       -chdir="$TF_DIR" output -raw ssh_user)
app_port=$(terraform       -chdir="$TF_DIR" output -raw app_port)
game_url=$(terraform       -chdir="$TF_DIR" output -raw game_url)

# Parse the full env maps from JSON so we don't have to list every key twice
env_prod_json=$(terraform  -chdir="$TF_DIR" output -json env_prod)
env_dev_json=$(terraform   -chdir="$TF_DIR" output -json env_dev)

# Helper: convert a JSON object {"K":"V",...} into KEY=VALUE lines
json_to_env() {
  python3 -c "
import sys, json
obj = json.load(sys.stdin)
for k, v in sorted(obj.items()):
    print(f'{k}={v}')
" <<< "$1"
}

# ── 3. Write .env (production) ───────────────────────────────────────────────

echo "==> Writing .env (production)..."
cat > "$REPO_ROOT/.env" <<EOF
# Auto-generated by provision-infrastructure.sh: $(date -Iseconds)
# Production environment — deployed to Lightsail instance ${instance_name} (${instance_ip})
# DO NOT COMMIT — contains secrets.

$(json_to_env "$env_prod_json")
EOF

# ── 4. Write development.env (local) ─────────────────────────────────────────

echo "==> Writing development.env (local)..."
cat > "$REPO_ROOT/development.env" <<EOF
# Auto-generated by provision-infrastructure.sh: $(date -Iseconds)
# Local development environment — used with: docker compose up
# DO NOT COMMIT — contains secrets.

$(json_to_env "$env_dev_json")
EOF

# ── 5. Copy prod env to instance ─────────────────────────────────────────────

SSH_KEY="${SSH_KEY_PATH:-$HOME/.ssh/lightsail/aura-farmers}"

if [[ -f "$SSH_KEY" ]]; then
  echo "==> Uploading .env to instance..."
  ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new \
    "${ssh_user}@${instance_ip}" "sudo mkdir -p /app && sudo chown ${ssh_user}:${ssh_user} /app"
  scp -i "$SSH_KEY" "$REPO_ROOT/.env" "${ssh_user}@${instance_ip}:/app/.env"
else
  echo "    SSH key not found at $SSH_KEY — skipping .env upload."
  echo "    Set SSH_KEY_PATH or manually copy .env to /app/.env on the instance."
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "==> Infrastructure ready."
printf   "    Game URL:    %s\n" "$game_url"
printf   "    Instance:    %s@%s\n" "$ssh_user" "$instance_ip"
printf   "    Prod env:    .env\n"
printf   "    Dev env:     development.env\n"
echo ""
echo "    To run locally:  docker compose up --build"
echo "    To deploy app:   ./scripts/deploy.sh"
